const data = [
  {
    "id": 1,
    "name": "Tesla Model S",
    "brand": "Tesla",
    "model": "Model S Plaid",
    "year": 2024,
    "category": "Electric Sedan",
    "amount": 79999,
    "quantity": 1,
    "fuelType": "Electric",
    "transmission": "Automatic",
    "color": "Pearl White",
    "image": "https://v2charge.com/wp-content/uploads/2024/08/tesla-model-s-precio.jpg"
  },
  {
    "id": 2,
    "name": "BMW i8",
    "brand": "BMW",
    "model": "i8 Roadster",
    "year": 2020,
    "category": "Hybrid Sports",
    "amount": 147500,
    "quantity": 1,
    "fuelType": "Hybrid",
    "transmission": "Automatic",
    "color": "Crystal White Pearl",
    "image": "https://www.evoindia.com/h-upload/uid/eeYk9IUi4J3GrzcUOyQAGuJGQcR8d4Wr.jpg"
  },
  {
    "id": 3,
    "name": "Audi A6",
    "brand": "Audi",
    "model": "A6 45 TFSI Quattro",
    "year": 2023,
    "category": "Luxury Sedan",
    "amount": 62000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Mythos Black Metallic",
    "image": "https://www.carblogindia.com/wp-content/uploads/2019/08/2019-Audi-A6.jpg"
  },
  {
    "id": 4,
    "name": "Mercedes-Benz C-Class",
    "brand": "Mercedes-Benz",
    "model": "C300 AMG Line",
    "year": 2023,
    "category": "Luxury Sedan",
    "amount": 55000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Obsidian Black",
    "image": "https://www.topgear.com/sites/default/files/2021/11/Mercedes_C300D_0000.jpg?w=1784&h=1004"
  },
  {
    "id": 5,
    "name": "Toyota Supra",
    "brand": "Toyota",
    "model": "GR Supra 3.0",
    "year": 2024,
    "category": "Sports Coupe",
    "amount": 58000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Renaissance Red",
    "image": "https://images.mktw.net/im-880532?width=1260&size=1.7777777777777777&pixel_ratio=1.5"
  },
  {
    "id": 6,
    "name": "Ford Mustang",
    "brand": "Ford",
    "model": "Mustang GT Fastback",
    "year": 2024,
    "category": "Muscle Car",
    "amount": 47000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Manual",
    "color": "Grabber Blue",
    "image": "https://www.topgear.com/sites/default/files/2023/07/24Mustang_Media_drive%20LA_23.jpg?w=1784&h=1004"
  },
  {
    "id": 7,
    "name": "Chevrolet Camaro",
    "brand": "Chevrolet",
    "model": "Camaro SS",
    "year": 2023,
    "category": "Muscle Car",
    "amount": 52000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Manual",
    "color": "Shock Yellow",
    "image": "https://www.topgear.com/sites/default/files/cars-car/carousel/2019/01/2018-sema-chevrolet-camaro-shock-020.jpg?w=1784&h=1004"
  },
  {
    "id": 8,
    "name": "Nissan GT-R",
    "brand": "Nissan",
    "model": "GT-R Premium",
    "year": 2022,
    "category": "Supercar",
    "amount": 113000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Gun Metallic",
    "image": "https://images.prismic.io/carwow/308bade4-bc03-4a29-a195-70631f39284a_2017+Nissan+GT-R+front+quarter+static.jpg?auto=format&cs=tinysrgb&fit=max&q=60"
  },
  {
    "id": 9,
    "name": "Porsche 911",
    "brand": "Porsche",
    "model": "911 Carrera S",
    "year": 2024,
    "category": "Sports Car",
    "amount": 128000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Guards Red",
    "image": "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d"
  },
  {
    "id": 10,
    "name": "Lamborghini Huracán",
    "brand": "Lamborghini",
    "model": "Huracán EVO",
    "year": 2023,
    "category": "Supercar",
    "amount": 230000,
    "quantity": 1,
    "fuelType": "Petrol",
    "transmission": "Automatic",
    "color": "Verde Mantis",
    "image": "https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9"
  }
]

export default data;